name: ğŸ“– Build HTML create artifact for review
on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Checking out the code ğŸ›’
      with:
        fetch-depth: 1
    - name: Set up Python 3.7 ğŸ
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies ğŸ‘¨â€ğŸ‘©â€ğŸ‘¦
      run: |
          python -m pip install --upgrade pip
          pip install -r REQUIREMENTS.txt
    - name: Build sphinx website ğŸ—
      run: |
          make html
    - name: Upload build artifact ğŸ“¦
      uses: actions/upload-artifact@v2
      with:
        name: HTML build
        path: output
